DATABASE NAME webskitters;

CREATE TABLE users(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	phone VARCHAR(15),
	image VARCHAR(255)
);

CREATE TABLE post_collection(
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title VARCHAR(300) NOT NULL,
description TEXT NOT NULL,
createdby VARCHAR(100),
 FOREIGN KEY (createdby) REFERENCES users(email)
)